### ISSUE TITLE
Windows build fails: PermissionsExt::mode() called without cfg(unix) gate in pty_shell.rs

### ISSUE THREAD

**Issue by taylor-wood-devo** [Strike48-public/pick#214]
## Summary

The v0.1.7 release run [28901816211](https://github.com/Strike48-public/pick/actions/runs/28901816211) failed on both Windows jobs (Desktop and Headless) with:

```
error[E0599]: no method named `mode` found for struct `Permissions` in the current scope
  --> crates\platform\src\desktop\pty_shell.rs:192:46
   |
192|                     .map(|m| m.permissions().mode() & 0o111 != 0)
   |                                              ^^^^ method not found in `Permissions`
```

## Root cause

`Permissions::mode()` comes from `std::os::unix::fs::PermissionsExt`, which is Unix-only. The import at the top of `crates/platform/src/desktop/pty_shell.rs` is already correctly gated:

```rust
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;
```

However, the executability check added at line 191-193 is **not** gated behind `cfg(unix)`, so Windows targets fail to compile.

The offending block was introduced in commit faefa8b (\"feat: parallel webwright, StrikeKit artifacts, LLM proxy auth\").

## Impact

- Windows Desktop and Windows Headless builds fail
- The release pipeline never reaches \"Create Release\", so no Windows artifacts are published for the tag
- All other targets (macOS x86_64/aarch64, Linux x86_64, Web) build cleanly

## Fix direction

Gate the mode-bit check behind `#[cfg(unix)]` and use a cross-platform fallback (e.g. `proot_path.exists()`) on Windows. The `SandboxBackend::Proot` branch isn't a realistic runtime path on Windows, but the code still has to compile there.

## Failed jobs

- Desktop (Windows): https://github.com/Strike48-public/pick/actions/runs/28901816211/job/85777115000
- Headless (Windows): https://github.com/Strike48-public/pick/actions/runs/28901816211/job/85777128218
